import type { ScenarioPreset } from "./types";

export const SCENARIOS: ScenarioPreset[] = [
  {
    id: "s1",
    title: "Dopahar mein bijli gayi",
    description: "2 PM, dhoop khub, grid fail — kya hoga?",
    timeHour: 14,
    dayType: "clear",
    batterySoc: 0.70,
    gridAvailable: false,
    appliancesOn: ["ac", "fan", "light", "fridge", "tv"],
    modeOutcomes: {
      "on-grid": "bad",
      "off-grid": "good",
      hybrid: "good",
    },
  },
  {
    id: "s2",
    title: "Raat mein bijli gayi",
    description: "10 PM, andhera, grid fail — battery kitna chalegi?",
    timeHour: 22,
    dayType: "clear",
    batterySoc: 0.80,
    gridAvailable: false,
    appliancesOn: ["fan", "light", "fridge", "tv"],
    modeOutcomes: {
      "on-grid": "bad",
      "off-grid": "warn",
      hybrid: "warn",
    },
  },
  {
    id: "s3",
    title: "Baarish ka din, sab chal raha",
    description: "12 PM, cloudy, full house load — solar kitna dega?",
    timeHour: 12,
    dayType: "cloudy",
    batterySoc: 0.60,
    gridAvailable: true,
    appliancesOn: ["ac", "fan", "light", "fridge", "tv"],
    modeOutcomes: {
      "on-grid": "warn",
      "off-grid": "warn",
      hybrid: "good",
    },
  },
  {
    id: "s4",
    title: "Battery full, dhoop khub hai",
    description: "12 PM clear, battery 100% — bijli kahan jayegi?",
    timeHour: 12,
    dayType: "clear",
    batterySoc: 1.0,
    gridAvailable: true,
    appliancesOn: ["fan", "light", "fridge", "tv"],
    modeOutcomes: {
      "on-grid": "good",
      "off-grid": "bad",
      hybrid: "good",
    },
  },
  {
    id: "s5",
    title: "EV + 2 AC + Geyser ek saath",
    description: "11 AM, sab ek saath chalaya — inverter ka kya hoga?",
    timeHour: 11,
    dayType: "clear",
    batterySoc: 0.70,
    gridAvailable: true,
    appliancesOn: ["ac", "fan", "light", "fridge", "tv", "geyser", "ev"],
    modeOutcomes: {
      "on-grid": "warn",
      "off-grid": "bad",
      hybrid: "bad",
    },
  },
  {
    id: "s6",
    title: "Shaam 6 baje 4-ghante ki cut",
    description: "6 PM sunset, 2 AC chal raha — 4 ghante battery chalegi?",
    timeHour: 18,
    dayType: "clear",
    batterySoc: 0.95,
    gridAvailable: false,
    appliancesOn: ["ac", "fan", "light", "fridge", "tv"],
    modeOutcomes: {
      "on-grid": "bad",
      "off-grid": "bad",
      hybrid: "good",
    },
  },
];
